version: "3"

services:

  rabbitmq-1:
    image: rabbitmq:3-management
    container_name: rabbitmq-1
    hostname: rabbitmq-1
    extra_hosts:
      - "rabbitmq-1:172.16.88.145"
      - "rabbitmq-2:172.16.88.146"
      - "rabbitmq-3:172.16.88.147"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=cluster_cookie
      - RABBITMQ_DEFAULT_USER=tungnd  
      - RABBITMQ_DEFAULT_PASS=tungnd
    network_mode: host
    privileged: true
    restart: unless-stopped

  rabbitmq-2:
    image: rabbitmq:3-management
    container_name: rabbitmq-2
    hostname: rabbitmq-2
    extra_hosts:
      - "rabbitmq-1:172.16.88.145"
      - "rabbitmq-2:172.16.88.146"
      - "rabbitmq-3:172.16.88.147"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=cluster_cookie
      - RABBITMQ_DEFAULT_USER=tungnd
      - RABBITMQ_DEFAULT_PASS=tungnd
    network_mode: host
    privileged: true
    restart: unless-stopped

  rabbitmq-3:
    image: rabbitmq:3-management
    container_name: rabbitmq-3
    hostname: rabbitmq-3
    extra_hosts:
      - "rabbitmq-1:172.16.88.145"
      - "rabbitmq-2:172.16.88.146"
      - "rabbitmq-3:172.16.88.147"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=cluster_cookie
      - RABBITMQ_DEFAULT_USER=tungnd
      - RABBITMQ_DEFAULT_PASS=tungnd
    network_mode: host
    privileged: true
    restart: unless-stopped
